config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',path_names: { sign_in: 'login', sign_out:, 'logout', sign_up: 'register' }
  
  resources :profiles 

  get 'home', to: 'pages#home' 
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "profiles#index"
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,  and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :set_title, :set_source

	def set_title
		@page_title = "Rails-App"
	end
	
	def set_source 
		session[:source] = params[:q] if params[:q]
	end	

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  layout "blog"
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
    @page_title = "Rails-Blog-Page"
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @user = Blog.find(params[:id])
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  layout "profile"
	def index
		@profile = Profile.all
    @page_title = "Rails-Profile-Page"
	end

	def new 
		@profile_item = Profile.new
	end

	def create
    	@profile_item = Profile.new(params.require(:profile).permit(:title, :subtitle, :body))
    	respond_to do |format|
      	if @profile_item.save
        	format.html { redirect_to profiles_url (@profile_item), notice: "Profile was successfully created." }
       	else
        	format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

def edit
	@profile_item = Profile.find(params[:id])
  end

 def update
 	@profile_item = Profile.find(params[:id])

    respond_to do |format|
      if @profile_item.update(params.require(:profile).permit(:title, :subtitle, :body))
        format.html { redirect_to profiles_url(@profile_item), notice: "Profile was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end
 
 def show 
 	 @profile_item = Profile.find(params[:id])
 end 


def destroy
    @profile_item = Profile.find(params[:id])
    @profile_item.destroy

    respond_to do |format|
      format.html { redirect_to profiles_path, notice: "Profile was successfully destroyed." }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog %></td> 
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td> 
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>
<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
  <%= @user %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Render pages from shared folder for nav items -->
    <%= render "shared/nav", nav: 'blog_nav' %>

    <!--Yield keyword used to render pages in the file-->
    <%= yield %>
      <!-- Devise authentication generator method  -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
  <!--Used to caputure session in the file   -->
    <% if session[:source] %>
     <p> Thanks for visiting <%= session[:source] %></p>
    <% end %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Change the link tag from application to blogs to show which stylesheet it should include in the mindex file for blogs -->
    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  <%= render "shared/nav", nav: 'blog_nav' %>
    <!--MOST IMPORTANT TO RENDER PAGES IN THE FILE-->
    <%= yield %>
    
  <!--Used to caputure session in the file   -->
    <% if session[:source] %>
     <p> Thanks for visiting <%= session[:source] %></p>
    <% end %>

  </body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <%= stylesheet_link_tag    'profiles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <!-- Partials -->
    <%= render "shared/nav", nav: 'profile_nav' %>
   
    <!--Render pages in the file-->
    <%= yield %>
    
    <!--Used to capture session in the file   -->
    <% if session[:source] %>
     <p> Thanks for visiting <%= session[:source] %></p>
    <% end %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/profiles/_form.html.erb
<%= form_for(@profile_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

 <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h2>Edit a Profile item </h2>
<%= render 'form', profile_item: @profile_item %>

app/views/profiles/index.html.erb
<h1>My Profile items </h1>

<p>
	<%= link_to "Create new Profile", new_profile_path %>
	<% @profile.each do | profile_item |  %>
		<h4><%= link_to profile_item.title, profile_path(profile_item) %></h4>
		<p><%= profile_item.subtitle %></p>
		<p><%= profile_item.body %></p>
		<p><%= image_tag profile_item.thumb_image unless profile_item.thumb_image.nil? %></p>
		<%= link_to "Edit", edit_profile_path(profile_item) %>	
		<%= link_to 'Delete', profile_item, method: :delete, data: { confirm: 'Are you sure?' } %>
		<hr>
    <%end %>
</p>  

app/views/profiles/new.html.erb
<h2>Create a new Profile </h2>
<%= render 'form', profile_item: @profile_item %>

app/views/profiles/show.html.erb
<%= image_tag @profile_item.main_image unless @profile_item.main_image.nil?%>
<h2><%=  @profile_item.title %></h2>
<p><%=  @profile_item.subtitle %></p>
<p><%=  @profile_item.body %></p>

app/views/shared/_nav.html.erb
<div class="<%= nav %>">

  <span><%=link_to 'Home', home_path %></span>
  <span><%=link_to 'About', about_path %></span>
  <span><%=link_to 'Contact', contact_path %></span>
  <span><%=link_to 'Blogs', blogs_path %></span>

</div>